version: '3.6'

services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - "/tmp/jdb:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  journal:
    image: cascade/journal-service
    ports:
      - "8080:8080"